### ISSUE TITLE
Delete macaroons when migrating wallets

### ISSUE THREAD

**Issue by AnotherDroog** [lncm/docker-lnd#1]
This builds and runs on arm32 with minor modifications. Great work!

I created this issue to point out that macaroons need to be regenerated when migrating a wallet.db between machines, otherwise lnd crashes upon unlocking.

Alternatively, wallet can be regenerated from seed too

**Comment by meeDamian** [comment]
yeah, this image still needs some work

**Comment by AnotherDroog** [comment]
I pushed some work-in-progress to invoicer-ui branch

**Comment by meeDamian** [comment]
This issue probably doesn't belong here, as it's probably a responsibility of `mana` operating within the exposed volume.
