### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by meeDamian** [lncm/docker-lnd#18]
Note all the changes made in #15.

**Comment by meeDamian** [comment]
This things desperately needs an overhaul!

Plus, ideally some (daily?) action should generate a complete list of current tags, and inject it into the `README.md`.

**Comment by nolim1t** [comment]
Another thing we should consider with the ```README.md``` is to put some documentation in it

**Comment by meeDamian** [comment]
I'd rather not copy the docs from `lnd` repo, how about adding a note to run `docker run --rm -it lncm/lnd:v0.9.1 --help` for info about possible configuration options?

**Comment by meeDamian** [comment]
Tags are up-to-date, and README.md sync action to Docker Hub exists, so… closing.
