### ISSUE TITLE
v0.12.0

### ISSUE THREAD

**Issue by AaronDewes** [lncm/docker-lnd#49]
It'd be great to have the 0.12.0 release here too, I think Umbrel also needed a new feature of that release, but I'm not sure which

**Comment by nolim1t** [comment]
on it

**Comment by nolim1t** [comment]
Hi, @AaronDewes .. I'm having some PGP key issues right now. 

They don't seem to verify up properly, nor match the documentation.

As a proponent of don't trust, verify. I'll dig a little further and try to see whats going on here.

**Comment by nolim1t** [comment]
You can track the issue [here](https://github.com/lightningnetwork/lnd/issues/4970)

**Comment by nolim1t** [comment]
[v0.12.0](https://github.com/lncm/docker-lnd/releases/tag/v0.12.0%2Bbuild1) is released. 

I'll keep it as pre-release until it has been tested thoroughly
