### ISSUE TITLE
Not able to create image on AARCH64

### ISSUE THREAD

**Issue by downet** [lncm/docker-lnd#51]
I am trying to build lnd on AARCH64 (RPI4), but getting error, because upx is not in packages for aarch64 (https://pkgs.alpinelinux.org/packages?name=upx&branch=v3.12&arch=aarch64):

```
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/aarch64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
  upx (missing):
    required by: world[upx]
```

I tried to build the image on my computer (x64) with ARG ARCH=aarch64 but that failed with:
```
Step 83/93 : FROM ${ARCH:+$ARCH/}alpine:${VER_ALPINE} AS final
manifest for aarch64/alpine:3.12 not found: manifest unknown: manifest unknown
```

Trying to compile it to test following issue https://github.com/lightningnetwork/lnd/issues/5114

**Comment by nolim1t** [comment]
Did you specify the follow ```--build-arg``` variables?

* ARCH
* GOARCH
* GOARM

**Comment by nolim1t** [comment]
However if you want to compile it to test [the following](https://github.com/lightningnetwork/lnd/issues/5114#issuecomment-801454703) you might find that the building the docker image might not help as it fetches the sources from github and builds and verifies this.

You'll probably need to install go and build it directly manually.

**Comment by downet** [comment]
I of course changed `ARG PKG=github.com/lightningnetwork/lnd` to minie repository where I did the change .. commented `RUN git verify-tag "$VERSION" || \` and I had to change also some other things to get it working :)

I've changed only following:
```
# Target CPU archtecture of built lnd binary
ARG ARCH
```
to
```
# Target CPU archtecture of built lnd binary
ARG ARCH=aarch64
```

Then I found from Github Workflow, that I should use rather `arm64v8`, but it still fails on `upx` which is not compiled in alpine for ARM. Is upx really needed or can I comment it out as well?

**Comment by nolim1t** [comment]
you can omit `upx`

**Comment by downet** [comment]
Thanks! :)
